name: endowrim_events
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  url_launcher: ^6.2.4
  firebase_core: ^2.24.2
  intl: ^0.19.0
  country_code_picker: ^3.0.0
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.6
  flutter_facebook_auth: ^6.0.4
  sign_in_with_apple: ^5.0.0
  image_picker: ^1.0.7
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.2.1
  twitter_login: ^4.4.2
  firebase_storage: ^11.6.0
  image_picker_web: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - lib/
    - lib/generated/
